# Generated by Django 5.2 on 2025-04-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sipariş Tipi')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_dismalting',
        ),
        migrations.AddField(
            model_name='product',
            name='is_dismantling',
            field=models.BooleanField(default=False, verbose_name='Sökülebilir mi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_plannable',
            field=models.BooleanField(default=False, verbose_name='Planlanabilir mi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sipariş Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('products', models.ManyToManyField(related_name='orders', to='core.product', verbose_name='Ürünler')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordertype', verbose_name='Sipariş Tipi')),
            ],
        ),
    ]
