import { typeInformation } from './models';
export const apiConfigs = {
  productAPI: {
    link         : '/get-product',
    metot        : 'GET',
    sorguIsim    : 'ProductAPI',
    queryable    : true,
    dtoTipId     : 'Product',
    dtoTipBilgi  : typeInformation.Product,
    sorguTipId   : 'ProductSerializer',
    sorguTipBilgi: typeInformation.ProductSerializer,
  },
  orderTypeAPI: {
    link         : '/get-order-type',
    metot        : 'GET',
    sorguIsim    : 'OrderTypeAPI',
    queryable    : true,
    dtoTipId     : 'OrderType',
    dtoTipBilgi  : typeInformation.OrderType,
    sorguTipId   : 'ProductSerializer',
    sorguTipBilgi: typeInformation.ProductSerializer,
  },
  deleteOrderAPI: {
    link         : '/delete-order',
    metot        : 'DELETE',
    sorguIsim    : 'DeleteOrderAPI',
    queryable    : false,
    dtoTipId     : 'Order',
    dtoTipBilgi  : typeInformation.Order,
    sorguTipId   : 'OrderSerializer',
    sorguTipBilgi: typeInformation.OrderSerializer,
  },
  createOrderAPI: {
    link         : '/create-order',
    metot        : 'POST',
    sorguIsim    : 'CreateOrderAPI',
    queryable    : false,
    dtoTipId     : 'Order',
    dtoTipBilgi  : typeInformation.Order,
    sorguTipId   : 'OrderSerializer',
    sorguTipBilgi: typeInformation.OrderSerializer,
  },
};